# Site settings
title: Alex Slavchev | DevOps & QA Engineer
email: aslavchev.android@gmail.com
url: https://aslavchev.github.io
description: "Personal site of Aleksandar Slavchev – Senior QA Engineer with 17+ years of experience in test automation, DevOps-aligned quality processes, and cross-platform software testing. Explore my projects, professional journey, and insights at the intersection of technology, sports, and performance."
keywords: "QA, Mobile , Web , DevOps, Forex, Finance, Futbol, Baseball, MLB, Wattbike, Sport Performance"
skills: "Web and Mobile QA - DevOps enthusiast - FX Trader - Football Coach"
meta_author: Alex Slavchev

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alex Slavchev | DevOps & QA Engineer
  location: Location
  social: Around the Web
  credits: About the Theme

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/aleksandar-slavchev-187313213/
    icon: linkedin
  - title: github
    url: https://github.com/aslavchev
    icon: github

# Postal address (add as many lines as necessary)
address:
  - line: Smilyan | Bulgaria 
  - line: Malaga  | Spain
  - line: Buenos Aires  | Argentina

# Credits content
credits: 'Freelancer is a free to use theme, open source Bootstrap theme created by <a href="https://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
